feat(package-info): correlate available pkg with gl features
* todo: handle urls

diff --git a/bin/package-info/garden-packages b/bin/package-info/garden-packages
--- a/bin/package-info/garden-packages
+++ b/bin/package-info/garden-packages
@@ -3,7 +3,6 @@
 set -Eeuo pipefail
 
 thisDir="$(dirname "$(readlink -f "${BASH_SOURCE}")")"
-latestVersion="$(${thisDir}/../garden-version --major).$(${thisDir}/../garden-version --minor)"
 
 REPO_VERSION=${REPO_VERSION:-"dev"}
 
@@ -28,33 +27,36 @@ done
 # $2: Output file name
 # $3: arch type (all, amd64, arm64)
 function get_package_file {
-    curl --silent -o ${2} "http://repo.gardenlinux.io/gardenlinux/dists/"${1}"/main/binary-"${3}"/Packages" || \
-	(echo "### Could not fetch Package file for ${1} from repo.gardenlinux.io" && exit 1)
 
-    grep -q "<Error><Code>NoSuchKey</Code>" ${2} && \
-	(echo "### Gardenlinux version ${1} does not exist on repo.gardenlinux.io" && exit 1)
+    curl --silent -o "${2}" "http://repo.gardenlinux.io/gardenlinux/dists/${1}/main/binary-${3}/Packages" || \
+	(echo "### Could not fetch Package file for ${1} from repo.gardenlinux.io" && exit 1);
+
+    grep -q "<Error><Code>NoSuchKey</Code>" "${2}" && \
+	(echo "### Gardenlinux version ${1} does not exist on repo.gardenlinux.io" && exit 1);
+
+    true
 }
 
 # $1: Packages.orig file downloaded from repo
 # $2: Arch (all, amd64, arm64)
 function filter_info {
 
-    cat $1 | grep -E "^Package:|^Version:" > Packages-file
+    grep -E "^Package:|^Version:" "$1" > Packages-file
 
-    cat Packages-file | grep -B 1 -E "^Version:.*garden-*" | grep -v '^--'  > Packages-"$2".gardenlinux
-    cat Packages-file | grep -B 1 -E "^Version:|!.*garden-*" | grep -v '^--'  > Packages-"$2".mirror
+    grep -B 1 -E "^Version:.*garden-*"  Packages-file | grep -v '^--'  > Packages-"$2".gardenlinux
+    awk 'NR==FNR{a[$0]=1;next}!a[$0]' Packages-"$2".gardenlinux Packages-file  > Packages-"$2".mirror
 
     rm Packages-file
 }
 
 mkdir -p "${thisDir}/tmp"
-trap "rm -rf ${thisDir}/tmp" EXIT
+trap 'rm -rf ${thisDir}/tmp' EXIT
 
 echo '### retrieve repo Package meta info'
 pushd "${thisDir}/tmp"
-get_package_file ${REPO_VERSION} Packages-all.orig all
-get_package_file ${REPO_VERSION} Packages-amd64.orig amd64
-get_package_file ${REPO_VERSION} Packages-arm64.orig arm64
+get_package_file "${REPO_VERSION}" Packages-all.orig all
+get_package_file "${REPO_VERSION}" Packages-amd64.orig amd64
+get_package_file "${REPO_VERSION}" Packages-arm64.orig arm64
 
 echo "### extract gardenlinux package information to separate file"
 filter_info Packages-all.orig all
@@ -62,14 +64,16 @@ filter_info Packages-amd64.orig amd64
 filter_info Packages-arm64.orig arm64
 
 echo "### Generate Packages YAML"
-${thisDir}/garden-packages-list-generator.py \
+"${thisDir}"/garden-packages-list-generator.py \
         --packages-mirror-all Packages-all.mirror\
        	--packages-mirror-amd64 Packages-amd64.mirror\
        	--packages-mirror-arm64 Packages-arm64.mirror\
         --packages-gl-all Packages-all.gardenlinux \
        	--packages-gl-amd64 Packages-amd64.gardenlinux \
        	--packages-gl-arm64 Packages-arm64.gardenlinux \
+	--feature-folder "${thisDir}"/../../features \
         --output ../available-gardenlinux-packages.yaml
+
 
 popd
 
